name: Favicon Cat
description: Test favicon in different browsers 测试各类favicon在不同浏览器的显示效果
timezone: Asia/Shanghai
# url: "https://favicontest.qweather.com"
baseurl: /
icp: 京ICP备15048401号-11
icp_url: https://beian.miit.gov.cn/
lang: zh_CN
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"

exclude:
- .gitignore
- .jekyll-cache
- README.md
- CNAME
- code
plugins:
- jekyll-seo-tag
- jekyll-sitemap
